# -*- coding: utf-8 -*-
"""pos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oH2ouBo8tg4jwX-P1qVy2b0y7jCMAsLZ
"""

#Python script to perform part-of-speech tagging on the sentence: 'NLP is amazing and fun to learn.' using SpaCy.

pip install spacy

import spacy
# Load the SpaCy English model
nlp = spacy.load('en_core_web_sm')
# Input sentence
sentence = "NLP is amazing and fun to learn."
# Process the sentence using the SpaCy pipeline
doc = nlp(sentence)
# Print part-of-speech tags for each token in the sentence
for token in doc:
    print(f'Token: {token.text}\tPOS: {token.pos_}\tTag: {token.tag_}')

import spacy
# Load the SpaCy English model
nlp = spacy.load('en_core_web_sm')
# Input sentence
sentence = "NLP is amazing and fun to learn."
# Process the sentence using the SpaCy pipeline
doc = nlp(sentence)
# Print part-of-speech tags and lemmatized words for each token
for token in doc:
    print(f'Token: {token.text}\tPOS: {token.pos_}\tTag: {token.tag_}\tLemma: {token.lemma_}')

